// try {
// int result = 10 ~/ 0;  // Gây lỗi chia cho 0
// } catch (e) {
// print('Caught an error: $e');
// } finally {
// print('This is always executed');
// }
